### ISSUE TITLE
converting svd scores to weights. scheme H

### ISSUE THREAD

**Issue by j-chou** [agupta0905/AGBsvdquartets#4]
Sorry, I posted on the wrong github page.

Shashank and I were talking about the svd scores to weights conversion, and shashank suggested the following scheme:
Let R=1/e^(svd_max-svd_med). Then
weight(q_min)=e^(R_(1-svd_min/svd_overall_max))
weight(q_med)=e^(R_(1-svd_med/svd_overall_max))
weight(q_max)=e^(R*(1-svd_max/svd_overall_max))
where svd_overall_max is the global maximum svd score. 
This will fix problems with svd_min = 0 and prevent the weights from being too large or too small. Let's call this new scheme H. In the python file we will need a list of all svd scores and compute the max of this list before assigning any weights to the quartets.

**Comment by redavids** [comment]
OK-but I'm still hoping you'll try something simple that always makes a
zero score the best:  Unless all three are zero, then toss out that
quartet.  I think A*Exp[-bx], where A is the biggest you want a score to b,
and b is a parameter that makes a bigger separation of scores near zero, is
simple and worth trying.  I'm attaching a pdf to remind you of the behavior
of this function for some choices of this function for various A and b.
Please add this to your list for the experiment.

On Fri, Apr 10, 2015 at 5:36 PM, j-chou notifications@github.com wrote:

> Sorry, I posted on the wrong github page.
> 
> Shashank and I were talking about the svd scores to weights conversion,
> and shashank suggested the following scheme:
> Let R=1/e^(svd_max-svd_med). Then
> weight(q_min)=e^(R
> _(1-svd_min/svd_overall_max)) weight(q_med)=e^(R_
> (1-svd_med/svd_overall_max))
> weight(q_max)=e^(R*(1-svd_max/svd_overall_max))
> where svd_overall_max is the global maximum svd score.
> This will fix problems with svd_min = 0 and prevent the weights from being
> too large or too small. Let's call this new scheme H. In the python file we
> will need a list of all svd scores and compute the max of this list before
> assigning any weights to the quartets.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agupta0905/AGBsvdquartets/issues/4.

## 

Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/

**Comment by redavids** [comment]
Of course x would be the svd score, so best score for example for
transformation 30*Exp(-100x) would be 30, and if svd_min = 0 get q_max =
30, vs. svd_max (worst) = 0.002 means q_min (worst) = 24.56

Depend on what values you are used to seeing for svd_min, svd_max you could
make best choice.

On Fri, Apr 10, 2015 at 6:08 PM, Ruth Davidson redavids@ncsu.edu wrote:

> OK-but I'm still hoping you'll try something simple that always makes a
> zero score the best:  Unless all three are zero, then toss out that
> quartet.  I think A*Exp[-bx], where A is the biggest you want a score to b,
> and b is a parameter that makes a bigger separation of scores near zero, is
> simple and worth trying.  I'm attaching a pdf to remind you of the behavior
> of this function for some choices of this function for various A and b.
> Please add this to your list for the experiment.
> 
> On Fri, Apr 10, 2015 at 5:36 PM, j-chou notifications@github.com wrote:
> 
> > Sorry, I posted on the wrong github page.
> > 
> > Shashank and I were talking about the svd scores to weights conversion,
> > and shashank suggested the following scheme:
> > Let R=1/e^(svd_max-svd_med). Then
> > weight(q_min)=e^(R
> > _(1-svd_min/svd_overall_max)) weight(q_med)=e^(R_
> > (1-svd_med/svd_overall_max))
> > weight(q_max)=e^(R*(1-svd_max/svd_overall_max))
> > where svd_overall_max is the global maximum svd score.
> > This will fix problems with svd_min = 0 and prevent the weights from
> > being too large or too small. Let's call this new scheme H. In the python
> > file we will need a list of all svd scores and compute the max of this list
> > before assigning any weights to the quartets.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/agupta0905/AGBsvdquartets/issues/4.
> 
> ## 
> 
> Ruth Davidson
> Department of Mathematics, University of Illinois Urbana-Champaign
> http://www.math.uiuc.edu/~redavid2/

## 

Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/

**Comment by redavids** [comment]
best choice for A and b I mean.  If biggest score you EVER see is 0.0002 maybe you want b = 150 or something.

**Comment by redavids** [comment]
Shashank and I decided on the phone that if the biggest SVD score you have
ever seen is 0.01, please set A = 10 and b = 100, then the best score will
be 10 and the worst score will be 3.7.

On Fri, Apr 10, 2015 at 6:13 PM, Ruth Davidson redavids@ncsu.edu wrote:

> Of course x would be the svd score, so best score for example for
> transformation 30*Exp(-100x) would be 30, and if svd_min = 0 get q_max =
> 30, vs. svd_max (worst) = 0.002 means q_min (worst) = 24.56
> 
> Depend on what values you are used to seeing for svd_min, svd_max you
> could make best choice.
> 
> On Fri, Apr 10, 2015 at 6:08 PM, Ruth Davidson redavids@ncsu.edu wrote:
> 
> > OK-but I'm still hoping you'll try something simple that always makes a
> > zero score the best:  Unless all three are zero, then toss out that
> > quartet.  I think A*Exp[-bx], where A is the biggest you want a score to b,
> > and b is a parameter that makes a bigger separation of scores near zero, is
> > simple and worth trying.  I'm attaching a pdf to remind you of the behavior
> > of this function for some choices of this function for various A and b.
> > Please add this to your list for the experiment.
> > 
> > On Fri, Apr 10, 2015 at 5:36 PM, j-chou notifications@github.com wrote:
> > 
> > > Sorry, I posted on the wrong github page.
> > > 
> > > Shashank and I were talking about the svd scores to weights conversion,
> > > and shashank suggested the following scheme:
> > > Let R=1/e^(svd_max-svd_med). Then
> > > weight(q_min)=e^(R
> > > _(1-svd_min/svd_overall_max)) weight(q_med)=e^(R_
> > > (1-svd_med/svd_overall_max))
> > > weight(q_max)=e^(R*(1-svd_max/svd_overall_max))
> > > where svd_overall_max is the global maximum svd score.
> > > This will fix problems with svd_min = 0 and prevent the weights from
> > > being too large or too small. Let's call this new scheme H. In the python
> > > file we will need a list of all svd scores and compute the max of this list
> > > before assigning any weights to the quartets.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/agupta0905/AGBsvdquartets/issues/4.
> > 
> > ## 
> > 
> > Ruth Davidson
> > Department of Mathematics, University of Illinois Urbana-Champaign
> > http://www.math.uiuc.edu/~redavid2/
> 
> ## 
> 
> Ruth Davidson
> Department of Mathematics, University of Illinois Urbana-Champaign
> http://www.math.uiuc.edu/~redavid2/

## 

Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/
